#!/bin/bash

# Setup Environment Script
# Creates .env file for real Solana transactions

echo "╔═══════════════════════════════════════════════════════╗"
echo "║  🔧 Setting Up Real Transaction Environment         ║"
echo "╚═══════════════════════════════════════════════════════╝"
echo ""

# Check if .env already exists
if [ -f ".env" ]; then
    echo "⚠️  .env file already exists."
    read -p "Do you want to overwrite it? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing .env file."
        exit 0
    fi
fi

# Create .env file
cat > .env << 'EOF'
# Agent-to-Agent Payment Router - Environment Configuration
# Generated by setup-env.sh

# =============================================================================
# 🔥 REAL TRANSACTIONS MODE
# =============================================================================
REAL_TRANSACTIONS=true

# =============================================================================
# ⛓️ SOLANA CONFIGURATION  
# =============================================================================
SOLANA_RPC_URL=https://api.devnet.solana.com
SOLANA_NETWORK=devnet

# =============================================================================
# 🤖 OPENAI API (Optional)
# =============================================================================
# Get your key at: https://platform.openai.com/api-keys
# Leave empty to use sentence extraction algorithm
OPENAI_API_KEY=

# =============================================================================
# 🌐 SERVICE PORTS
# =============================================================================
REGISTRY_PORT=3001
ROUTER_PORT=3002
TRANSLATOR_PORT=3100
SUMMARIZER_PORT=3101
ANALYZER_PORT=3102
WEB_PORT=3000

# =============================================================================
# 📊 LOGGING
# =============================================================================
LOG_LEVEL=info
VERBOSE_TRANSACTIONS=true
EOF

echo "✅ Created .env file"
echo ""
echo "📝 Configuration:"
echo "   • Real Transactions: ENABLED"
echo "   • Network: Solana Devnet"
echo "   • OpenAI: Not configured (using fallback)"
echo ""
echo "🔑 Optional: Add OpenAI API Key"
echo "   1. Get key: https://platform.openai.com/api-keys"
echo "   2. Edit .env file"
echo "   3. Set: OPENAI_API_KEY=sk-your-key-here"
echo ""
echo "💰 Next Steps:"
echo "   1. Run: npm run setup:wallets"
echo "   2. Fund wallets with devnet SOL"
echo "   3. Start services: npm run start:all"
echo ""

